all:
	@(cd runtime; make --no-print-directory)
	@(cd engine;  make --no-print-directory)
	@(cd main;    make --no-print-directory)
clean:
	@(cd runtime; make --no-print-directory clean)
	@(cd engine;  make --no-print-directory clean)
	@(cd main;    make --no-print-directory clean)
